# Generated by Django 4.1.3 on 2022-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=150)),
                ('fiyat', models.FloatField()),
                ('aciklama', models.TextField()),
                ('resim', models.ImageField(upload_to='images')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.CharField(choices=[('macpro', 'Mac Pro'), ('macstudio', 'Mac Studio'), ('macbookpro', 'Macbook Pro'), ('macbookair', 'Macbook Air'), ('imac', 'iMac')], default='Mac Pro', max_length=100)),
            ],
        ),
    ]
